### ISSUE TITLE
ConstraintLayout Compose LintDebug fails

### ISSUE THREAD

**Issue by riggaroo** [android/snippets#117]
Running `./gradlew :compose:snippets:lintDebug` and `ConstraintLayout` snippets throw the following error: 
`Github/snippets/compose/snippets/src/main/java/com/example/compose/snippets/layouts/ConstraintLayoutSnippets.kt: Error: Unexpected failure during lint analysis of ConstraintLayoutSnippets.kt (this is a bug in lint or one of the libraries it depends on)`

Running with --stacktrace, gives the following error:

```
java.lang.AbstractMethodError: Method androidx/constraintlayout/compose/lint/ConstraintLayoutDslDetectorKt$findChildIdentifier$1.afterVisitSimpleNameReferenceExpression(Lorg/jetbrains/uast/USimpleNameReferenceExpression;)V is abstract
        at androidx.constraintlayout.compose.lint.ConstraintLayoutDslDetectorKt$findChildIdentifier$1.afterVisitSimpleNameReferenceExpression(ConstraintLayoutDslDetector.kt)
        at org.jetbrains.uast.kotlin.KotlinUSimpleReferenceExpression.accept(KotlinUSimpleReferenceExpression.kt:47)
        at androidx.constraintlayout.compose.lint.ConstraintLayoutDslDetectorKt.findChildIdentifier(ConstraintLayoutDslDetector.kt:732)
        at androidx.constraintlayout.compose.lint.ConstraintLayoutDslDetector$createUastHandler$1.detectChainParamsUsage(ConstraintLayoutDslDetector.kt:338)
        at androidx.constraintlayout.compose.lint.ConstraintLayoutDslDetector$createUastHandler$1.visitCallExpression(ConstraintLayoutDslDetector.kt:145)
        at com.android.tools.lint.client.api.UElementVisitor$DispatchPsiVisitor.visitCallExpression(UElementVisitor.kt:523)
        at com.android.tools.lint.client.api.UElementVisitor$DelegatingPsiVisitor.visitCallExpression(UElementVisitor.kt:1071)
        at org.jetbrains.uast.kotlin.KotlinUFunctionCallExpression.accept(KotlinUFunctionCallExpression.kt:165)
        at org.jetbrains.uast.kotlin.KotlinULocalVariable.accept(KotlinULocalVariable.kt:46)
        at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
        at org.jetbrains.uast.UDeclarationsExpression$DefaultImpls.accept(UDeclarationsExpression.kt:22)
        at org.jetbrains.uast.kotlin.KotlinUDeclarationsExpression.accept(KotlinUDeclarationsExpression.kt:10)
        at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
        at org.jetbrains.uast.UBlockExpression$DefaultImpls.accept(UBlockExpression.kt:21)
```

**Comment by bentrengrove** [comment]
Confirmed the above fixed it so closing
